#!/bin/bash

toilet -f future "Youtube" | lolcat

lblue='\033[1;34m'
gray='\033[1;30m'
lgray='\033[0;37m'
cyan='\033[0;36m'
lcyan='\033[1;36m'
red='\033[1;31m'
yellow='\033[1;33m'
green='\033[1;32m'
blue='\033[1;34m'
purple='\033[1;35m'

echo -e "             $gray 2019 by Z@3imPro"
echo ""
echo -e "   $gray Download All Videos from$red YOUTUBE$purple Mp3$lblue Mp4"
echo ""
echo -e "         $red ($yellow 1$red )$purple Audio only "
echo -e "         $red ($yellow 2$red )$lcyan 480p SD Videos"
echo -e "         $red ($yellow 3$red )$yellow 720p HD Video"
echo -e "         $red ($yellow 4$red )$green 1080p Full HD Video"
echo -e ""
echo -e -n "$cyan Choose Number > ";command='-no-mtime -o /sdcard/Videos/%(title)s.%(ext)s -f'
read option

if [ "$option" -eq "1" ]
then
    echo -e "$purple  Starting Download audio m4a Best Quality .."
    echo "$command 140" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "2" ]
then
    echo -e "$lcyan Starting Download Quality SD 480..."
    echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "3" ]
then
    echo -e "$yellow Starting Download Quality HD 720..."
    echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "4" ]
then
    echo -e "$green Starting Download Best Quality Full HD..."
    echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
fi
